package com.dy.downlibrary;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dy.downlibrary.DownLoadTaskInfo;

import com.dy.downlibrary.DownLoadTaskInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downLoadTaskInfoDaoConfig;

    private final DownLoadTaskInfoDao downLoadTaskInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downLoadTaskInfoDaoConfig = daoConfigMap.get(DownLoadTaskInfoDao.class).clone();
        downLoadTaskInfoDaoConfig.initIdentityScope(type);

        downLoadTaskInfoDao = new DownLoadTaskInfoDao(downLoadTaskInfoDaoConfig, this);

        registerDao(DownLoadTaskInfo.class, downLoadTaskInfoDao);
    }
    
    public void clear() {
        downLoadTaskInfoDaoConfig.clearIdentityScope();
    }

    public DownLoadTaskInfoDao getDownLoadTaskInfoDao() {
        return downLoadTaskInfoDao;
    }

}
